// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package mobi.openddr.examples.gwtcanvasdemo.module.client.requestfactory;

import mobi.openddr.examples.gwtcanvasdemo.module.client.requestfactory.request.PersonRequest;
import com.google.web.bindery.requestfactory.shared.LoggingRequest;
import com.google.web.bindery.requestfactory.shared.RequestFactory;

/**
 * The main request factory.
 */
public interface ApplicationRequestFactory extends RequestFactory {
	
	/**
	 * @return a GWT logging request.
	 */
	LoggingRequest loggingRequest();
	
	PersonRequest personRequest();
}
